- name: Deploy Owncloud
  hosts: localhost
  tasks:
    - name: Install required packages for ownCloud
      yum: 
        name: "{{items}}"
        state: present
      vars:
        items:
            - httpd
            - mariadb
            - mariadb-server
            - MySQL-python
            - php
            - php-common
            - php-curl
            - php-xml
            - php-mcrypt
            - php-imap
            - php-gd
            - php-mbstring
            - php-ldap
            - php-pdo
            - php-mysql
            - php-intl
            - php-process
            - php-xml
            - php-json
            - php-pear-DB
            - php-pecl-imagick
            - mysql
            - mariadb-devel
            - php-zip
            - php-pecl-zip

    - name: enable mariadb server
      service: 
        name: mariadb
        enabled: yes

    - name: Start mariadb server
      service: 
        name: mariadb
        state: started
        
  
    - name: Add rpm-key from ownCloud
      rpm_key:
        key: http://download.owncloud.org/download/repositories/stable/CentOS_7/repodata/repomd.xml.key
        state: present

    - name: Add ownCloud repository
      yum_repository:
        name: ownCloud
        description: EPEL Yum Repo
        gpgcheck: yes
        baseurl: http://download.owncloud.org/download/repositories/stable/CentOS_7/
        gpgkey: http://download.owncloud.org/download/repositories/stable/CentOS_7/repodata/repomd.xml.key
        state: present
        
    - name: the clean command to make yum aware of the change
      command: "yum clean expire-cache"
      
    - name: Install / Download ownCloud
      yum:
        name: owncloud-files
        state: present
    
    - name: Create 'owncloud' Database
      mysql_db:
        name: owncloud
        state: present

    - name: Change password of owncloud database user
      command: >
        mysql -u root --execute="GRANT ALL ON owncloud.* to 'owncloud'@'localhost' IDENTIFIED BY 'password'; FLUSH PRIVILEGES;"
        
        
    - name: Install required packages for ownCloud
      yum:
        name: "{{repo}}"
        state: present
      vars:
        repo:
            - http://rpms.remirepo.net/enterprise/remi-release-7.rpm
            - yum-utils

    - name: Install php 70
      command: "yum-config-manager --enable remi-php70"

    - name: upgrade all packages
      yum:
        name: '*'
        state: latest
        
    - name: open port 80 for httpd access
      firewalld:
        service: http
        permanent: true
        state: enabled
    - name: Restart the firewalld service to load in the 
      service:
        name: firewalld
        state: restarted 
        
    
    - name:  httpd is restart
      service: 
        name: httpd
        state: restarted
        

