- name: Deploy
  remote_user: root
  hosts: fuga_vms
  become: yes
  tasks:
    - name: Create mount dir
      file:
        path: /var/www/owncloud/data
        state: directory

    - name: Format volume
      filesystem:
        fstype: ext4
        dev: /dev/vdb

    - name: Create mountpoint
      mount:
        path: /var/www/owncloud/data
        src: /dev/vdb
        fstype: ext4
        state: mounted

    - name: Update permissions
      file:
        path: /var/www/owncloud/data
        state: directory
        owner: www-data
        group: www-data

    - name: Install required packages for ownCloud
      yum: name={{item}} state=present update-cache=yes
      with_items:
           - httpd
           - mariadb-server
           - libapache2-mod-php7.0
           - openssl
           - php-imagick
           - php7.0-common
           - php7.0-curl
           - php7.0-gd
           - php7.0-imap
           - php7.0-intl
           - php7.0-json
           - php7.0-ldap
           - php7.0-mbstring
           - php7.0-mcrypt
           - php7.0-mysql
           - php7.0-pgsql
           - php-smbclient
           - php-ssh2
           - php7.0-sqlite3
           - php7.0-xml
           - php7.0-zip
           - python3-mysqldb
           - python3-dev
           - libmysqlclient-dev

    - name: Add rpm-key from ownCloud
      rpm_key:
        url: https://download.owncloud.org/download/repositories/stable/CentOS_7/repodata/repomd.xml.key
        state: present

    - name: Add ownCloud repository
      yum_repository:
        baseurl: https://download.owncloud.org/download/repositories/stable/CentOS_7/ /
        state: present

    - name: Install / Download ownCloud
      yum:
        name: owncloud
        update-cache: yes

    - name: Create 'owncloud' Database
      mysql_db:
        name: owncloud
        state: present

    - name: Change password of owncloud database user
      command: >
        mysql -u root --execute="GRANT ALL ON owncloud.* to 'owncloud'@'localhost' IDENTIFIED BY 'password'; FLUSH PRIVILEGES;"

    - name: Copy ownCloud Apache config
      template:
        src: owncloud.j2
        dest: "/etc/httpd/sites-available/owncloud.conf"

    - name: Create syslink to available-sites
      become: yes
      file:
        src: "/etc/httpd/sites-available/owncloud.conf"
        dest: "/etc/httpd/sites-enabled/owncloud.conf"
        state: link

    - name: Restart Apache
      command: "systemctl reload httpd"

