- name: Deploy Owncloud
  hosts: host1
  tasks:
    - name: Install required packages for ownCloud
      yum: 
        name: "{{items}}"
        state: present
      vars:
        items:
           - httpd
           - mariadb-server
           - openssl
           - php-common
           - php-curl
           - php-gd
           - php-imap
           - php-intl
           - php-json
           - php-ldap
           - php-mbstring
           - php-mcrypt
           - php-mysql
           - php-pgsql
           - php-xml
           - php-zip

    - name: Add rpm-key from ownCloud
      rpm_key:
        url: https://download.owncloud.org/download/repositories/stable/CentOS_7/repodata/repomd.xml.key
        state: present

    - name: Add ownCloud repository
      yum_repository:
        baseurl: https://download.owncloud.org/download/repositories/stable/CentOS_7/ /
        state: present

    - name: Install / Download ownCloud
      yum:
        name: owncloud
        state: present

    - name: Create 'owncloud' Database
      mysql_db:
        name: owncloud
        state: present

    - name: Change password of owncloud database user
      command: >
        mysql -u root --execute="GRANT ALL ON owncloud.* to 'owncloud'@'localhost' IDENTIFIED BY 'password'; FLUSH PRIVILEGES;"

    - name: Restart Apache
      command: "systemctl reload httpd"

