- name: Deploy Owncloud
  hosts: host1
  tasks:
    - name: Install required packages for ownCloud
      yum: 
        name: "{{items}}"
        state: present
      vars:
        items:
            - httpd
            - mariadb-server
            - openssl
            - php-common
            - php-curl
            - php-xml
            - php-common
            - php-mcrypt
            - php-pgsql
            - php-imap
            - php-gd
            - php-mbstring
            - php-ldap
            - php-pdo
            - php-mysql
            - php-intl
            - php-process
            - php-xml

    - name: Add rpm-key from ownCloud
      rpm_key:
        key: http://download.owncloud.org/download/repositories/stable/CentOS_7/repodata/repomd.xml.key
        state: present

    - name: Add ownCloud repository
      yum_repository:
        name: ownCloud
        description: EPEL Yum Repo
        gpgcheck: yes
        baseurl: http://download.owncloud.org/download/repositories/stable/CentOS_7/
        gpgkey: http://download.owncloud.org/download/repositories/stable/CentOS_7/repodata/repomd.xml.key
        state: present

    - name: Install / Download ownCloud
      yum:
        name: owncloud-files
        state: present

    - name: Create 'owncloud' Database
      mysql_db:
        name: owncloud
        state: present

    - name: Change password of owncloud database user
      command: >
        mysql -u root --execute="GRANT ALL ON owncloud.* to 'owncloud'@'localhost' IDENTIFIED BY 'password'; FLUSH PRIVILEGES;"

    - name: Restart Apache
      command: "systemctl reload httpd"

